# Generated by Django 2.2.6 on 2019-10-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('meds_name', models.CharField(max_length=50)),
                ('meds_strength', models.CharField(max_length=30)),
                ('meds_dir', models.CharField(max_length=20)),
                ('meds_status', models.CharField(max_length=20)),
                ('meds_date', models.DateField()),
            ],
        ),
    ]
